AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetSongDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-data/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetSongData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get-song-data
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetSongDataApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Data Function function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-song-data/"
  GetSongDataFunction:
    Description: "Get Data Lambda Function ARN"
    Value: !GetAtt GetSongDataFunction.Arn
  GetSongDataFunctionIamRole:
    Description: "Implicit IAM Role created for Get Data function"
    Value: !GetAtt GetSongDataFunctionRole.Arn
